language: java
services:
- docker
before_install:
- chmod +x mvnw
- docker build -t gato-negro .
- docker images
addons:
  sonarcloud:
    organization: d3c184f43c8a925376c733917659019ca8e96c49
    token:
      secure: csjS3xsSxul3I6yNwjqDD4iL9sjFYMHY3WFRPUYzI6unF5CZmu02OlRRUcLDeY9COYwaVAka6Gt0mh8bg1jP81OFkTqXAioVypHHOqeO5ED9ZbbbhbfGVGAKSdDFMRYum9Oe2jA8SgYEWVSks2LFj6ECf3uayBGDeZBVLy/14WlsTqrFVzrzAoh5uuoz8Yxk0BDuQffJ+v9nu2Y01VC+3mGPg5+2ll524AQky1hRdX8nUiybJurd9GaQgG+PWFR+Qj/PfK9ySZFEoxaFmPbE8cWNM2WIsV+MRImRAKf4RNkmbkF2H9vhjV9KyS1Y2bcYtHJLLMA8rP5mQoK2Qba3TdvHRiVYQCehmk7XrRbi2ZN12SuHWxiqyuUHUrWGKu+h22VFPPzBY+9PHw9oQ923m6rJHTwLoS0Km5bfoSFkMUvtmUuzJePtbWlQkncvg4oM9ujUNXlztBi9tFZJV8UBTV/m4HRdezW0GyMLuOPKWezI1eyTgzyybFD6mj+E+vwaqi8vnwRSIoEEzzhpSBh11r79C8UnWrBiQHzvWxK9rOFI3T1IY6+4Gn0tmPxxXKvRq2X19J/xwpgU2TewBq2A3xxgQxQyIKYCWP5ZXFtxpyVstwYHZ15G5NNbXYDozZ+9EP9v30FucN6mBxbvwB3BXnszqbwtwaKbu2sRsOd9dwQ=
env:
  global:
  - secure: gKxFgAhFrxvL51eo8f9BP5cwHzVK4Kt6l6lm/ZF7K0GL6ZqFsZkrs0LtaguI/uMEy3VISY0hfFNjRJ5mBmlWNNiVqMKKly+1riag9/+1poa2UOOyL6ZpLjHOiAC/Pch07sU3nLVpVtBn0JRXuJPIKMC7UKDWkkKAJZMjIJYKU2UMQf2defT8nOn1wQxP1m8HcI9akzjTjXnXr6bfp8HRfFLwz9p0T4gA7TqenSdD8LxIYY7g9/vTMLt7d1TVmCSO5wGnteGmucYJyv/uNQZvIwKbUeXUne9Tak4WTdXhJQ91Wg/YGerT7ndjbPIChq2LlTIchA37bthmwCKrE7VP6/9Q2eGlvwUSheJaEtx6r4PjYN6Ie6+0PvA/aXIPEarKF00vpeQNWAYp75JvzD1RqRml2fxOb8AAE67h5zPY1GgHdq0LYReTlCDLbYHTFDvNF2sqJKaYuAHU8JuSu+mMHIn/lLIqh0sM0JDFOtBFUpgYNhix4OKUVDi3dTtDA/BGcv8u3Wz5sbjVkM8TAuvAaChXSd7jcy31p/Svd68dL/lEbV8QqoP7ecvrYgsNa0Ub0EozGOV3SxBWP8TonV8dw3S5LKuSwbl0odx1ol92rvi1FxRcPiheWLY06RuN6AzL1DvJM/+3dUzWQuNgEbABy7xhdp/YEpNqeAg4nRZwE2U=
  - secure: gb1vj7QKfLfM0dsx61i1eOm8a5fCNS245mV5Tc03nkgTugOe5j3sP4KdrXaSM4Th0fz90Th9QZwUOEbyMEj37J1FMCeZPl82idFfUAUDH1Hfnc24wmb3ao5WY+kqji0Dpyx+Au4t/ock1M+EX0EcimaM1yoPaEoFCNnmSgqbfZdc3N5fO42Bf15mm4ZGCXxcAemSTIEIl/3IRQWfPBINj98ZIQGsmoPFxsU2iy2U+HH8tEvKooOyhWmnb5fg8iYnL2aq5dQacFb0bK+ODqiClCqw2qV3dRDovCDiSLkdY/OVSnU772TTYYDK3srSUFheo5nkd05gkkZydhMqqbTi/KfDxGu9OtMRBqNuCYyD80PxzfKK/IASaKfVM1rJLcYT1VBx1hpUVTcUgC1AO8pAtkSHW/QnO/lGFln9Qn1P979ocJWnab80HWARyy6tYvxK00DNBYm1q2U/r/3GAXTcvfUMpZDxwxsrnF+bUL38vQVR2ZpMmFfZVZFaPOBQIWpM77RwKB/e2MsQseHPwFiy3ykyX5vsrTpJ/7ogkQoWpNs/FIyFFfv6keu7YJC797NZAAD3Jvcijo6CvrysMHl3gTR+/syVfidwByK6YwTSX0o0KsSzHu2PPwyopGGiyJpNyYcnv2Ssjcf1SCS1zjoEH1BBWRtIbqmujEuygS+Nf+4=
deploy:
  provider: script
  script: bash docker_push
  on:
    branch: develop
