FROM adoptopenjdk/maven-openjdk11
COPY src src
COPY pom.xml pom.xml
RUN mvn clean install


 
 
# 2. Just using the build artifact and then removing the build-container
#FROM openjdk:11-jdk

#VOLUME /tmp
 
# Add Spring Boot app.jar to Container
#COPY --from=0 "/home/app/target/GatoNegroSonar-*-SNAPSHOT.jar" app.jar
 
# Fire up our Spring Boot app by default
#CMD [ "sh", "-c", "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar /app.jar" ]